#!/bin/bash

# Mobile Testing Guide for Siani Voice Conversation

echo "📱 Siani Mobile Testing Guide"
echo "============================="
echo ""

echo "🎯 Prerequisites:"
echo "  ✅ Backend running (./dev.sh)"
echo "  ✅ OpenAI API key configured"
echo "  ✅ Expo Go app installed on your phone"
echo ""

echo "📲 Option 1: Test on Physical Device (Recommended)"
echo "--------------------------------------------------"
echo ""
echo "1. Install Expo Go app:"
echo "   • iOS: https://apps.apple.com/app/expo-go/id982107779"
echo "   • Android: https://play.google.com/store/apps/details?id=host.exp.exponent"
echo ""
echo "2. Start mobile development server:"
echo "   cd packages/mobile"
echo "   npm start"
echo ""
echo "3. Scan QR code with:"
echo "   • iOS: Camera app"
echo "   • Android: Expo Go app"
echo ""
echo "4. Navigate to Siani screen and test voice recording"
echo ""

echo "💻 Option 2: Test on Simulator/Emulator"
echo "----------------------------------------"
echo ""
echo "iOS Simulator:"
echo "   cd packages/mobile"
echo "   npm run ios"
echo ""
echo "Android Emulator:"
echo "   cd packages/mobile"
echo "   npm run android"
echo ""

echo "🎤 Testing Voice Features:"
echo "-------------------------"
echo ""
echo "1. Login with test account:"
echo "   Email: john.doe@example.com"
echo "   Password: patient123"
echo ""
echo "2. Navigate to Siani screen (modal)"
echo ""
echo "3. Test voice recording:"
echo "   • Tap and hold 'Tap to speak' button"
echo "   • Speak clearly"
echo "   • Release to send"
echo "   • Wait for Siani's response"
echo "   • Audio should auto-play"
echo ""
echo "4. Verify:"
echo "   ✅ Transcription accuracy"
echo "   ✅ Emotion detection (color indicator)"
echo "   ✅ Voice response plays automatically"
echo "   ✅ Conversation history persists"
echo "   ✅ Avatar reacts to emotion"
echo ""

echo "🐛 Troubleshooting:"
echo "------------------"
echo ""
echo "Issue: 'Network request failed'"
echo "  → Check backend is running: curl http://localhost:3000/health"
echo "  → Update EXPO_PUBLIC_API_URL in packages/mobile/.env"
echo "  → For physical device, use your computer's IP:"
echo "    EXPO_PUBLIC_API_URL=http://YOUR_IP:3000"
echo ""
echo "Issue: 'Microphone permission denied'"
echo "  → Allow microphone access in phone settings"
echo "  → Restart Expo Go app"
echo ""
echo "Issue: 'Failed to synthesize speech'"
echo "  → Check OpenAI API key in backend/.env"
echo "  → Check backend logs: tail -f backend.log"
echo ""

echo "📊 Backend Monitoring:"
echo "---------------------"
echo ""
echo "Watch backend logs:"
echo "  tail -f backend.log | grep -E '(Siani|TTS|emotion)'"
echo ""
echo "Test API directly:"
echo "  bash test-siani-conversation.sh"
echo ""

echo "🎨 Mobile App Features to Test:"
echo "-------------------------------"
echo ""
echo "✅ Voice Recording"
echo "   • Press and hold to record"
echo "   • Visual feedback (pulse animation)"
echo "   • Haptic feedback on press/release"
echo ""
echo "✅ Emotion Detection"
echo "   • CALM = Teal dot"
echo "   • GUARDED = Pink dot"
echo "   • LIT = Gold dot"
echo ""
echo "✅ Audio Playback"
echo "   • Automatic playback of Siani's response"
echo "   • Base64 audio data URL"
echo ""
echo "✅ Conversation UI"
echo "   • User messages (right, dark gray)"
echo "   • Siani messages (left, purple glow)"
echo "   • Scrolls to latest message"
echo ""
echo "✅ Avatar"
echo "   • Emotion-aware animations"
echo "   • Size: 120px"
echo "   • Centered at top"
echo ""

echo "🚀 Next Steps After Testing:"
echo "----------------------------"
echo ""
echo "1. Add WebSocket streaming for real-time audio"
echo "2. Implement waveform visualization during recording"
echo "3. Add haptic feedback patterns for different emotions"
echo "4. Enable background recording"
echo "5. Add offline queue for messages"
echo "6. Implement streak tracking"
echo ""

echo "💡 Quick Start:"
echo "--------------"
echo "  cd packages/mobile"
echo "  npm start"
echo ""
echo "Then scan QR code with Expo Go app!"
